CREATE DATABASE FINANCIAMENTO
USE FINANCIAMENTO

DROP TABLE TB_LANCAMENTO

CREATE TABLE TB_LANCAMENTO (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Data DATETIME NOT NULL,
	Valor DECIMAL(18,2) NOT NULL,
	Descricao VARCHAR(50) NOT NULL,
	Conta VARCHAR(20) NOT NULL,
	Tipo CHAR(1) NOT NULL,
)

SELECT CONTA, TIPO, VALOR FROM TB_LANCAMENTO WHERE FORMAT(DATA, 'yyyy-MM') = '2020-12'
GROUP BY CONTA, TIPO, VALOR

DELETE FROM TB_LANCAMENTO

INSERT INTO TB_LANCAMENTO (Data, Valor, Descricao, Conta, Tipo)
	SELECT	CONVERT(DATETIME, '2020/12/22', 101),
			100.00,
			'Achei no bolso da calça',
			'Carteira',
			'c'

INSERT INTO TB_LANCAMENTO (Data, Valor, Descricao, Conta, Tipo)
	SELECT	CONVERT(DATETIME, '2020/12/09', 101),
			10000.00,
			'Salário Best Soft',
			'Itau',
			'c'

INSERT INTO TB_LANCAMENTO (Data, Valor, Descricao, Conta, Tipo)
	SELECT	CONVERT(DATETIME, '2020/12/09', 101),
			50.00,
			'Tarifa da conta',
			'Itau',
			'd'
